import { OperatorRegistry, type OperatorDefinition } from "../core/operator.js";
import type { DimensionSpec } from "../core/semantics.js";

const triggerDimension: DimensionSpec = {
  id: "trigger-event",
  label: "Trigger event",
  valueKind: "event",
  measurement: "nominal",
  unit: "event",
  missingPolicy: "gap",
};

const noteDimension: DimensionSpec = {
  id: "note-event",
  label: "Note event",
  valueKind: "event",
  measurement: "nominal",
  unit: "event",
  missingPolicy: "gap",
};

const scalarDimension: DimensionSpec = {
  id: "unitless-scalar",
  label: "Unitless scalar",
  valueKind: "scalar",
  measurement: "interval",
  unit: "1",
  missingPolicy: "error",
};

export const OPERATOR_DEFINITIONS: readonly OperatorDefinition[] = [
  {
    type: "rhythm.euclidean",
    version: 1,
    name: "Euclidean Distribution",
    category: "Rhythm",
    description: "Distributes a selected number of onsets as evenly as possible across a pulse grid.",
    deterministic: true,
    conformanceClass: "exact",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "euclidean-step-v1", keyVersion: 1 },
    budget: { dimensions: ["events"], profileId: "agl-mvp-budget", profileVersion: 1 },
    inputs: [],
    outputs: [{ id: "pattern", name: "Trigger pattern", type: "pattern.trigger", required: true, dimension: triggerDimension }],
    parameters: [
      { id: "steps", name: "Steps", description: "Pulse-grid length.", kind: "integer", defaultValue: 16, minimum: 1, maximum: 256 },
      { id: "pulses", name: "Pulses", description: "Number of active onsets.", kind: "integer", defaultValue: 5, minimum: 0, maximum: 256 },
      { id: "rotation", name: "Rotation", description: "Cyclic phase offset.", kind: "integer", defaultValue: 0, minimum: -256, maximum: 256 },
    ],
  },
  {
    type: "rhythm.risset",
    version: 1,
    name: "Risset Tempo Staircase",
    category: "Perceptual illusion",
    description: "Applies logarithmic rate layering, analytic phase, and a compact crossfade envelope to create an endless-tempo construction.",
    deterministic: true,
    conformanceClass: "profileNumeric",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "risset-source-layer-cycle-v1", keyVersion: 1 },
    budget: { dimensions: ["events", "audio-density"], profileId: "agl-mvp-budget", profileVersion: 1 },
    evidenceStatus: "qualified",
    inputs: [{ id: "pattern", name: "Source pattern", type: "pattern.trigger", required: false, dimension: triggerDimension }],
    outputs: [
      { id: "pattern", name: "Layered trigger pattern", type: "pattern.trigger", required: true, dimension: triggerDimension },
      { id: "geometry", name: "Log-tempo visualization", type: "visualization", required: true },
      { id: "provenance", name: "Layer and phase trace", type: "provenance", required: true },
    ],
    parameters: [
      { id: "referenceBpm", name: "Reference BPM", description: "Center tempo for the one-pulse reference source.", kind: "number", defaultValue: 120, minimum: 40, maximum: 240 },
      { id: "equivalenceRatio", name: "Equivalence ratio", description: "2 is the canonical Risset tempo octave; other ratios are generalized barberpole tempo.", kind: "number", defaultValue: 2, minimum: 1.01, maximum: 4 },
      { id: "cycleSeconds", name: "Cycle", description: "Seconds required to traverse one equivalence interval.", kind: "number", defaultValue: 20, minimum: 8, maximum: 40 },
      { id: "windowHalfWidth", name: "Window half-width", description: "Compact raised-cosine support in log-tempo units.", kind: "number", defaultValue: 2, minimum: 0.51, maximum: 5 },
      { id: "normalization", name: "Normalization", description: "Linear partition is canonical; nominal equal-power is a comparison.", kind: "enum", defaultValue: "linear-partition", options: ["linear-partition", "nominal-equal-power"] },
      { id: "direction", name: "Direction", description: "Sign of local log-rate slope.", kind: "enum", defaultValue: "accelerate", options: ["accelerate", "decelerate"] },
    ],
  },
  {
    type: "rhythm.subdivision-shed",
    version: 1,
    name: "Subdivision Shedding",
    category: "Rhythm mapping",
    description: "Deterministically filters selected subdivisions without altering core Risset semantics.",
    deterministic: true,
    conformanceClass: "exact",
    mappingStage: "transform",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "successor-mapped", keySchema: "source-event-v1", keyVersion: 1, successorMapVersion: 1 },
    inputs: [{ id: "pattern", name: "Input pattern", type: "pattern.trigger", required: true, dimension: triggerDimension }],
    outputs: [{ id: "pattern", name: "Filtered pattern", type: "pattern.trigger", required: true, dimension: triggerDimension }],
    parameters: [{ id: "factor", name: "Factor", description: "Deterministic subdivision retention factor.", kind: "integer", defaultValue: 2, minimum: 1, maximum: 16 }],
  },
  {
    type: "rhythm.metric-overlay",
    version: 1,
    name: "Metric Overlay",
    category: "Rhythm mapping",
    description: "Adds an explicit metrical or polyrhythmic layer, including experimental 3:2 ambiguity.",
    deterministic: true,
    conformanceClass: "exact",
    mappingStage: "transform",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "metric-overlay-event-v1", keyVersion: 1 },
    evidenceStatus: "experimental",
    inputs: [{ id: "pattern", name: "Input pattern", type: "pattern.trigger", required: true, dimension: triggerDimension }],
    outputs: [{ id: "pattern", name: "Overlay pattern", type: "pattern.trigger", required: true, dimension: triggerDimension }],
    parameters: [{ id: "ratio", name: "Ratio", description: "Metric relationship.", kind: "enum", defaultValue: "3:2", options: ["3:2", "4:3", "5:4"] }],
  },
  {
    type: "rhythm.anchor",
    version: 1,
    name: "Reference Anchor Pulse",
    category: "Rhythm control",
    description: "Adds a stable objective pulse for controlled comparison.",
    deterministic: true,
    conformanceClass: "exact",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "anchor-cycle-v1", keyVersion: 1 },
    inputs: [],
    outputs: [{ id: "pattern", name: "Anchor pattern", type: "pattern.trigger", required: true, dimension: triggerDimension }],
    parameters: [{ id: "bpm", name: "BPM", description: "Anchor tempo.", kind: "number", defaultValue: 120, minimum: 20, maximum: 300 }],
  },
  {
    type: "pitch.shepard",
    version: 1,
    name: "Shepard Pitch Coupling",
    category: "Pitch illusion",
    description: "Adds an independently switchable circular pitch-direction cue.",
    deterministic: true,
    conformanceClass: "profileNumeric",
    mappingStage: "target",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "successor-mapped", keySchema: "source-event-v1", keyVersion: 1, successorMapVersion: 1 },
    evidenceStatus: "experimental",
    inputs: [{ id: "pattern", name: "Input pattern", type: "pattern.note", required: true, dimension: noteDimension }],
    outputs: [{ id: "pattern", name: "Pitch-coupled pattern", type: "pattern.note", required: true, dimension: noteDimension }],
    parameters: [{ id: "octaves", name: "Octaves", description: "Number of spectral octave components.", kind: "integer", defaultValue: 6, minimum: 3, maximum: 10 }],
  },
  {
    type: "harmony.tonnetz-walk",
    version: 1,
    name: "Tonnetz Walk",
    category: "Harmony",
    description: "Traverses a lattice whose axes encode interval relationships.",
    deterministic: true,
    conformanceClass: "exact",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "tonnetz-path-step-v1", keyVersion: 1 },
    inputs: [{ id: "path", name: "Graph path", type: "math.graph", required: false }],
    outputs: [{ id: "notes", name: "Chord pattern", type: "pattern.note", required: true, dimension: noteDimension }],
    parameters: [
      { id: "origin", name: "Origin", description: "Origin pitch class.", kind: "integer", defaultValue: 0, minimum: 0, maximum: 11 },
      { id: "quality", name: "Quality", description: "Triad quality.", kind: "enum", defaultValue: "major", options: ["major", "minor"] },
    ],
  },
  {
    type: "structure.fractal-motif",
    version: 1,
    name: "Fractal Motif",
    category: "Structure",
    description: "Recursively nests transformed motifs at progressively smaller time scales.",
    deterministic: true,
    conformanceClass: "exact",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "recursive-ancestry-v1", keyVersion: 1 },
    budget: { dimensions: ["events", "recursion", "memory"], profileId: "agl-mvp-budget", profileVersion: 1 },
    inputs: [{ id: "seed", name: "Seed motif", type: "math.sequence", required: false }],
    outputs: [{ id: "notes", name: "Nested notes", type: "pattern.note", required: true, dimension: noteDimension }],
    parameters: [
      { id: "depth", name: "Depth", description: "Recursion depth.", kind: "integer", defaultValue: 3, minimum: 1, maximum: 8 },
      { id: "eventLimit", name: "Event limit", description: "Safety bound for generated events.", kind: "integer", defaultValue: 4096, minimum: 16, maximum: 100000 },
    ],
  },
  {
    type: "structure.cellular-automaton",
    version: 1,
    name: "Cellular Automaton Orchestra",
    category: "Emergent systems",
    description: "Emits exact cellular state and derived features for explicit downstream sonification.",
    deterministic: true,
    conformanceClass: "exact",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "ca-cell-generation-v1", keyVersion: 1 },
    budget: { dimensions: ["iterations", "geometry", "memory"], profileId: "agl-mvp-budget", profileVersion: 1 },
    inputs: [],
    outputs: [
      { id: "features", name: "Feature table", type: "math.feature-table", required: true },
      { id: "grid", name: "Automaton grid", type: "visualization", required: true },
    ],
    parameters: [
      { id: "rule", name: "Rule", description: "Elementary automaton rule number.", kind: "integer", defaultValue: 30, minimum: 0, maximum: 255 },
      { id: "width", name: "Width", description: "Cells per generation.", kind: "integer", defaultValue: 32, minimum: 4, maximum: 128 },
    ],
  },
  {
    type: "dynamics.lorenz",
    version: 1,
    name: "Lorenz Dynamics",
    category: "Dynamical systems",
    description: "Integrates a Lorenz trajectory and emits typed coordinates and geometry; musical mapping is downstream.",
    deterministic: true,
    conformanceClass: "profileNumeric",
    temporal: { kind: "pointwise" },
    generatedIdentity: { kind: "stable", keySchema: "lorenz-sample-index-v1", keyVersion: 1 },
    budget: { dimensions: ["iterations", "geometry", "memory"], profileId: "agl-mvp-budget", profileVersion: 1 },
    inputs: [],
    outputs: [
      { id: "coordinates", name: "Control coordinates", type: "signal.control", required: true },
      { id: "geometry", name: "Attractor geometry", type: "math.geometry", required: true },
    ],
    parameters: [
      { id: "sigma", name: "Sigma", description: "Prandtl-like parameter.", kind: "number", defaultValue: 10, minimum: 0.1, maximum: 50 },
      { id: "rho", name: "Rho", description: "Rayleigh-like parameter.", kind: "number", defaultValue: 28, minimum: 0.1, maximum: 80 },
      { id: "beta", name: "Beta", description: "Geometric damping parameter.", kind: "number", defaultValue: 2.6666666667, minimum: 0.1, maximum: 20 },
    ],
  },
  {
    type: "mapping.normalize.fixed",
    version: 1,
    name: "Fixed-Bounds Normalization",
    category: "Mapping",
    description: "Maps a declared source interval into a target interval with explicit clipping diagnostics.",
    deterministic: true,
    conformanceClass: "profileNumeric",
    mappingStage: "normalize",
    temporal: { kind: "pointwise" },
    inputs: [{ id: "signal", name: "Source signal", type: "signal.control", required: true, dimension: scalarDimension }],
    outputs: [{ id: "signal", name: "Normalized signal", type: "signal.control", required: true, dimension: scalarDimension }],
    parameters: [
      { id: "minimum", name: "Minimum", description: "Declared lower bound.", kind: "number", defaultValue: 0 },
      { id: "maximum", name: "Maximum", description: "Declared upper bound.", kind: "number", defaultValue: 1 },
    ],
  },
  {
    type: "mapping.smooth.one-pole",
    version: 1,
    name: "One-Pole Smoothing",
    category: "Mapping",
    description: "Causal smoothing parameterized by a time constant rather than sample-dependent alpha.",
    deterministic: true,
    conformanceClass: "profileNumeric",
    mappingStage: "smooth",
    temporal: { kind: "causal-stateful", reset: "transport-start" },
    inputs: [{ id: "signal", name: "Source signal", type: "signal.control", required: true, dimension: scalarDimension }],
    outputs: [{ id: "signal", name: "Smoothed signal", type: "signal.control", required: true, dimension: scalarDimension }],
    parameters: [{ id: "timeConstant", name: "Time constant", description: "Smoothing time constant in seconds.", kind: "number", defaultValue: 0.1, minimum: 0, maximum: 10 }],
  },
  {
    type: "mapping.quantize.scalar",
    version: 1,
    name: "Scalar Quantizer",
    category: "Mapping",
    description: "Quantizes a continuous signal with an explicit tie rule.",
    deterministic: true,
    conformanceClass: "profileNumeric",
    mappingStage: "quantize-threshold",
    temporal: { kind: "pointwise" },
    inputs: [{ id: "signal", name: "Source signal", type: "signal.control", required: true, dimension: scalarDimension }],
    outputs: [{ id: "signal", name: "Quantized signal", type: "signal.control", required: true, dimension: scalarDimension }],
    parameters: [
      { id: "steps", name: "Steps", description: "Number of bins.", kind: "integer", defaultValue: 12, minimum: 1, maximum: 1024 },
      { id: "tieRule", name: "Tie rule", description: "Deterministic midpoint behavior.", kind: "enum", defaultValue: "tie-lower", options: ["tie-lower", "tie-upper", "tie-even-index"] },
    ],
  },
  {
    type: "constraints.musical",
    version: 1,
    name: "Musical Constraint Set",
    category: "Constraints",
    description: "Applies deterministic range, scale, density, polyphony, and voice-leading constraints with traceable deltas.",
    deterministic: true,
    conformanceClass: "profileNumeric",
    mappingStage: "constrain",
    temporal: { kind: "pointwise" },
    inputs: [{ id: "notes", name: "Candidate notes", type: "pattern.note", required: true, dimension: noteDimension }],
    outputs: [
      { id: "notes", name: "Constrained notes", type: "pattern.note", required: true, dimension: noteDimension },
      { id: "trace", name: "Constraint trace", type: "provenance", required: true },
    ],
    parameters: [{ id: "profile", name: "Profile", description: "Named explicit constraint bundle.", kind: "enum", defaultValue: "musical", options: ["faithful", "musical", "pedagogical", "experimental"] }],
  },
] as const;

export function createDefaultOperatorRegistry(): OperatorRegistry {
  const registry = new OperatorRegistry(true);
  for (const definition of OPERATOR_DEFINITIONS) {
    registry.register(definition);
  }
  registry.seal();
  return registry;
}
